language: go

go:
- 1.10.x

env:
- DEP_VERSION="0.4.1"

before_install:
- curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64
  -o $GOPATH/bin/dep
- chmod +x $GOPATH/bin/dep
- go get github.com/mitchellh/gox

install:
- dep ensure

script:
- go build
- ./test.sh testdata/*
- if [ -n "$TRAVIS_TAG" ]; then gox; fi

deploy:
  provider: releases
  api_key:
    secure: CcOpA6L8ieSn18M7JBVLXI0ZV43WfuJwnbsGK8dVkvKrOJcfx5DC0xyGHUZazQrRfN44WwSXeSvk2R3P3eeVJMROtFQ3h4ZmM04wj8tjeENGnvnlHFOik1k8hecrQzBK3qeFGQHcVf3/6Ur+T2RMl9bVaerTdbvq2/CuF/X8Jhvuk59RpAajfZ4wnk3aIMpSNfsyRKoMKOoyfvqqhTzUcMcuxtFiFgWjhS591/V4gzZjatmUdskXFNfkM9ASMt3stxg9dCzpdPSfHrzEKb+JL1JN7wcV5iuCLLFO+l069/z6ZnQcxRx0ydrJDELNMWExUug40eJGjH/8KnpjDCEkYWPqbgZW96KaCxY63wqdxNCZn41XG03IUkFckKXt1fbMUcyJXIVz6QPnibuOvA1BOVuKZq4P5Ff4zT0pC30T+Dd5U1bxyWJ8Nn06sDjVEUr2BoCoBOBYefkAkNvgpk7PHLf4Kq8LKsD9nt634Qab5QZpa+cEBPoz8JrEm2OSjpmEkrRSUPEsQwMqDZMMezPpo4ODdFRMoi+xyXkAM9V7HclIa7K+Ag9eNQqa8srtBkgt+J1HzpYiIt72sGdyoEXLgmF5kJjCQeOjHATum2QaKHtUJKHU2+q19Oi0aC38a4AwHhvtslRSmiJutYhqmRZDdLMgZUc0OPuWoM65Ze9ST+Y=
  file_glob: true
  file: rjsone_*
  skip_cleanup: true
  on:
    repo: groklearning/rjsone
    tags: true
